### ISSUE TITLE
`gconf2` missing on Ubuntu 23.10

### ISSUE THREAD

**Issue by lifeisafractal** [gantsign/ansible-role-visual-studio-code-extensions#119]
Ubuntu has removed the deprecated gconf2 package. I'm not sure why vscode required it for the CLI, but simply removing it from `apt.yml` seems to have everything work fine. I'll open a PR for this too.

**Comment by lifeisafractal** [comment]
Fixed in #120.

**Comment by freemanjp** [comment]
@lifeisafractal thanks for the PR. You can find your fix in version [2.5.0](https://github.com/gantsign/ansible-role-visual-studio-code-extensions/releases/tag/2.5.0) of this role.
