### ISSUE TITLE
Provide ability to disable  extension(s)

### ISSUE THREAD

**Issue by NileshGule** [gantsign/ansible-role-visual-studio-code-extensions#15]
Provide an ability to disable an installed extension(s)

**Comment by freemanjp** [comment]
The Visual Studio Code `--disable-extensions` flag doesn't take a parameter for individual extensions and isn't a persistent change (i.e. it's something you can specify when starting Visual Studio Code), so I don't see how this can be implemented.

**Comment by NileshGule** [comment]
I agree that it is not possible to individually disable the extension (except from the IDE itself). When I tried the --disable-extensions command on terminal it did not seem to work as expected. The issue can be closed.
