### ISSUE TITLE
A later version is already installed error

### ISSUE THREAD

**Issue by PaulBurridge-kcom** [gantsign/ansible-role-visual-studio-code-extensions#27]
Hi, 

I am running your script via vagrant and Ansible local, I often re-provision when tweaking or adding Ansible scripts. Due to the fact that Visual Studio Code auto updates I get the failure below. Would it be possible to add an optional flag to not fail if a newer version is installed?

```
TASK [gantsign.visual-studio-code : install Visual Studio Code] ****************
fatal: [default]: FAILED! => {"changed": false, "msg": "A later version is already installed"}
        to retry, use: --limit @/Provisioning/main.retry
```

Thanks.

**Comment by freemanjp** [comment]
@PaulBurridge-kcom , thanks for your feedback; I think you'll find this issue is fixed by version [4.0.0](https://github.com/gantsign/ansible-role-visual-studio-code/releases/tag/4.0.0) of the [gantsign.visual-studio-code](https://github.com/gantsign/ansible-role-visual-studio-code) role.
