### ISSUE TITLE
`code-insiders` version : ) By the way, thanks for this extension!

### ISSUE THREAD

**Issue by shaneholloman** [gantsign/ansible-role-visual-studio-code-extensions#65]
This is a super idea. @gantsign If you have will and time, a [`code-insiders` version](https://code.visualstudio.com/insiders/) would be superb!

**Comment by freemanjp** [comment]
@shaneholloman thanks for raising this issue.

It may take me a few days but I'll look into it.

**Comment by freemanjp** [comment]
@shaneholloman you can find the feature you requested in the [2.2.0](https://github.com/gantsign/ansible-role-visual-studio-code-extensions/releases/tag/2.2.0) release of this role.
